### ISSUE TITLE
Problem with building war

### ISSUE THREAD

**Issue by majkelo** [kensiprell/grails-drools#9]
I found a strange problem when packing project into a war: after adding drools to buildconfig it somehow affects classes from src/groovy (like excluding them from buildpath or something):
http://stackoverflow.com/questions/30888875/can-not-build-war-from-grails-project

Problem is definitely connected with drools because I revert commits and it occures only with statement:
compile ":drools:1.1.0"

moreover when I run project by 'grails run-app' it runs smoothly without any problem...

**Comment by kensiprell** [comment]
Please be specific with exactly what's happening: full path to the affected files in your source code and where they end up or where they were expected to end up in the war.

The only war creating action is here: https://github.com/kensiprell/grails-drools/blob/master/scripts/_Events.groovy#L21. As you can see it uses the same method to copy files to the class path in development mode, only the destination is different. It should only copy *.drl and *.rule files to WEB-INF/classes before the war is created.

I tested this by deploying a [sample app](https://github.com/kensiprell/grails-drools-sample) war to tomcat and verifying the controller tests passed.

Ken

**Comment by majkelo** [comment]
Thanks for your fast answer Ken!
First I thought it's connected with only Enums from my src/groovy but after moving all of them to domain classes (it wasn't the best solution, but acceptable sacrifice) I've got 'unable to resolve class' errors from simple groovy classes from my src/groovy... It looks like all classes from src/groovy aren't anymore visible for domain classes or views. 
I have attached stacktrace verbose in stackoverflow topic listed in previous post. Do you need anything else? I'm not sure how to properly debug 'grails war' command...

**Comment by kensiprell** [comment]
Mike,

I'm almost positive this is not related to the plugin. It certainly couldn't have replaced the OUT_CODEC property. The plugin only copies files that end in .drl or .rule. I can't think of anything it does that would lead to the behavior you describe.

A war file is simply an archive that you can extract with an archive utility and examine its directory and file structure.

You mentioned reverting commits, but a better test might have been to just comment out the plugin dependency. Something else in those commits could be responsible for the error.

Ken

**Comment by majkelo** [comment]
Ken,

I commented out drools from Buildconfig and... 'grails war' ended succesfully (but of course there is a runtime error when I execute functions which import DroolsService). 
Right now I've separated drools plugin to local repo and try to manipulate it's code but still get errors.

Mike

**Comment by kensiprell** [comment]
Mike,

I need detailed info on the errors: the code your using to call the service, the stacktrace, etc. I really don't think you need the change the plugin code. 

Ken

**Comment by majkelo** [comment]
Ken,
I have separated example code from app: https://github.com/majkelo/AgroErrorRepo
If you comment in BuildConfig.groovy line: *compile ":drools:1.1.0"* project will compile successfully (problem dissapeared after removing views, so probably the best test command'd be *"grails compile ---gsp"*).

**Comment by kensiprell** [comment]
Mike,

I'll take a look, but it might be tomorrow before I can get to it.

Ken

**Comment by majkelo** [comment]
Ken,
sure and thanks for your effort!
Mike

**Comment by kensiprell** [comment]
Mike,

I just took a quick look, and we might have dependency conflicts with the cxf plugin. I won't be able to test it for several hours, if at all today, but what happens if you comment out the cxf dependency and try to compile?

Ken

**Comment by majkelo** [comment]
Ken, 
I've just tried it - unfortunatelly it doesn't work. It still *grails compile* successfully but it is crashing when *grails compile ---gsp* . 
Mike

**Comment by kensiprell** [comment]
Mike,

Does eu.ventocg.agrowapp.alert.Alert require any dependencies that could conflict with the versions in the plugin's BuildConfog.groovy?

Ken

**Comment by kensiprell** [comment]
Mike,

I cloned your repo, but of course it wouldn't compile for me because I don't have your AlertType and TimeFormat classes. However, once I deleted those entries in your views and domain class, ```grails compile ---gsp``` worked for me. As I alluded to in my previous post, I think there's a dependency version conflict between those classes  and either something in the plugin's [BuildConfig.groovy](https://github.com/kensiprell/grails-drools/blob/master/grails-app/conf/BuildConfig.groovy#L20-L89) or maybe the [kie-spring](https://repo1.maven.org/maven2/org/kie/kie-spring/6.2.0.Final/kie-spring-6.2.0.Final.pom) module.

Ken

**Comment by majkelo** [comment]
Ken,
that's the problem: these classes are in project, in: *https://github.com/majkelo/AgroErrorRepo/tree/master/src/groovy/eu/ventocg/agrowapp*. If you comment out drools lib the project'd build successfully. I'm still not sure where is the problem.
Mike

**Comment by kensiprell** [comment]
Mike,

I'm not familiar with the ---gsp flag, so I'm simply assuming that those
classes must be compiled and on the classpath before ```grails compile
---gsp``` will work. I didn't look for them last night in your source tree
when compilation failed because I thought they were pulled in by the
dependency manager.


However, I still don't understand why commenting out the drools plugin
dependency would allow the ---gsp compile to work. I'll take another look
tonight.

Ken

**Comment by majkelo** [comment]
Ken,
the same situation occures when I try to execute **grails war** or **grails run-war** (so in every situation when gsp views are precompiled. **grails compile ---gsp** is just the fastest test). 
But the project is packing and running correctly if I comment out drools. I'm not sure how drools lib could affect compiling process of views.
Mike

**Comment by kensiprell** [comment]
Mike,

If I comment out [this line](https://github.com/kensiprell/grails-drools/blob/master/scripts/_Events.groovy#L15) and reinstall the plugin, ```compile ---gsp``` works. However, I can't figure out why. The script it calls finishes without any errors. I'm just guessing, but maybe the Grails compiler is trying to access a directory or file that's locked.

Have you attached a debugger? It's too late for me now, but it's failing in [this method](http://grails.github.io/grails-doc/2.4.x/api/org/codehaus/groovy/grails/project/compiler/GrailsProjectCompiler.html#compileGroovyPages(java.lang.String,%20def)).

Ken

**Comment by majkelo** [comment]
Ken,
I'll try tomorrow and look for an explanation. 
However thanks for a hint, cause I was really stuck on this...
Mike

**Comment by kensiprell** [comment]
Mike,

I finally found the [source code](https://github.com/grails/grails-core/blob/2.4.x/grails-project-api/src/main/groovy/org/codehaus/groovy/grails/project/compiler/GrailsProjectCompiler.groovy#L428)  and the [ant task](https://github.com/grails/grails-core/blob/23461301a310956df6c8f7c49f12d189b906f55e/grails-web-gsp/src/main/groovy/org/grails/web/pages/GroovyPageCompilerTask.groovy) for the GSP compiler. However, I don't see why the plugin would cause the method to fail, especially since it doesn't have a views directory. You might want to take a look in case I overlooked something. My attention to detail is not what it used to be.

When I get home tonight I'll try adding a view to the plugin and see what effect that has.

Ken

**Comment by kensiprell** [comment]
Mike,

I fixed the compile problem. See [here](https://github.com/kensiprell/grails-drools/commit/fcbf764d18de2bb7d8b89fa324916d117c13c95c#diff-d64b3b2f712ddb8296942a1099c56ff0) for the details. I don't remember why I originally created the ```GroovyShell``` the way I did, but now all tests pass using ```new GroovyClassLoader()```, including testing with your app.

I published the plugin to GrailsCentral, but the [plugin page](http://grails.org/plugin/drools) is still showing 1.1.0, so I'm not sure if it will download automatically. If the plugin page isn't updated by tomorrow, I'll let the Grails team know.

Sorry this took so long!
Ken
